version: '3'
services: 
  buyer:
    restart: always
    image: buyer-api:latest
    container_name: buyer
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8888:8888"
    # network_mode: host
  common:
    restart: always
    image: common-api:latest
    container_name: common
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8886:8886"
    # network_mode: host
  im-api:
    restart: always
    image: im-api:latest
    container_name: im-api
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8885:8885"
    # network_mode: host

  seller:
    restart: always
    image: seller-api:latest
    container_name: seller
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8889:8889"
    # network_mode: host

  manager:
    restart: always
    image: manager-api:latest
    container_name: manager
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8887:8887"
    # network_mode: host

  xxl-job:
    restart: always
    image: xxl-job:latest
    container_name: xxl-job
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "9001:9001"
    # network_mode: host


  admin:
    restart: always
    image: admin:latest
    container_name: admin
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    ports: 
      - "8000:8000"
    # network_mode: host

  #wap-ui:
  #  restart: always
  #  image: wap-ui:latest
  #  container_name: wap-ui
  #  network_mode: host

  #buyer-ui:
  #  restart: always
  #  image: buyer-ui:latest
  #  container_name: buyer-ui
  #  network_mode: host

  #seller-ui:
  #  restart: always
  #  image: seller-ui:latest
  #  container_name: seller-ui
  #  network_mode: host

  #manager-ui:
  #  restart: always
  #  image: manager-ui:latest
  #  container_name: manager-ui
  #  network_mode: host

