version: '3'
services: 
  buyer:
    restart: always
    image: buyer-api:latest
    container_name: buyer
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC

  common:
    restart: always
    image: common-api:latest
    container_name: common
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    network_mode: host

  seller:
    restart: always
    image: seller-api:latest
    container_name: seller
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    network_mode: host

  manager:
    restart: always
    image: manager-api:latest
    container_name: manager
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    network_mode: host

  wap-ui:
    restart: always
    image: wap-ui:latest
    container_name: wap-ui
    network_mode: host

  buyer-ui:
    restart: always
    image: buyer-ui:latest
    container_name: buyer-ui
    network_mode: host

  seller-ui:
    restart: always
    image: seller-ui:latest
    container_name: seller-ui
    network_mode: host

  manager-ui:
    restart: always
    image: manager-ui:latest
    container_name: manager-ui
    network_mode: host

